(fix) Wrong symbol param for getPublicTrades request
bitfinexcom/bfx-report-ui pull request #626
Opened 2023-03-30 14:36 UTC by alexstotsky

Task: https://app.asana.com/0/1163495710802945/1204298582161856/f
#### Description:
- [x] Fixes issues with incorrect pairs formatting and providing a `symbol` param for the `getPublicTrades` request in some cases
- [x] Adjusts `Symbol Filter` width to fit better for all available pairs
#### Before:
<img width="1134" alt="fix_symbol_before" src="https://user-images.githubusercontent.com/41899906/228871455-ff9f8b69-7831-4824-b213-1354c1af7034.png">

#### After:
<img width="1371" alt="fix_symbol_after" src="https://user-images.githubusercontent.com/41899906/228871519-2be8b5f2-344c-4c2d-a7b9-c6a98dbdc9c4.png">

2023-03-30 15:26 UTC, elvis-poggi approved these changes

2023-03-31 05:39 UTC, ezewer requested changes
The way this was map i dont think its entirely correct. 
Not that this PR introduce the errors, but that the errors where displayed by last changes. 
Logic should be the following: 
1 - From Api we receive pairs, currencies, inactiveSymbols, mapSymbols, inactiveCurrencies
Pairs before being sent to backend should add the t as to get the tranding pair t${pair}
2 - As to display pairs, we should: 
 a - look if pair has its equivalent in mapSymbols
 b - Split the pair into 2 currencies (get each currency from currencies array), this might have ':' as to split or be pair.length === 6 (3 and 3) 
3 - Currencies have an ID and a name to display
4 - In movements display all the symbols 
5 - For rest, filters the one that dont are in trading pairs. 
6 - For the places now added ad `f${symbol.id}` (only the filtered ones)

2023-03-31 05:39 UTC, ezewer commented on src/state/symbols/utils/index.js
> +export const addPrefix = (symbol = '', isFunding = false) => (
So i would definitely change this. 
What would do is the following: 
1 - Add t to each result from pairs, that should be the trading pair. 
```console
const tradingPairs = pairs.map(p => `t${p}`)
```

2023-03-31 05:39 UTC, ezewer commented on src/state/symbols/utils/index.js
> +export const deformatPair = pair => ((pair.length === 7) ? pair.replace(':', '') : pair)
Same that comment below, there should not be a need to replace ':'

2023-03-31 09:38 UTC, ezewer approved these changes
Following our recent deliberations, we have decided to proceed with merging this pull request as an interim patch to address the immediate concern. Meanwhile, we will continue working towards a comprehensive solution that effectively resolves all legacy case scenarios.

2023-03-31 09:41 UTC, merged